baseURL = 'https://dulynotedatucsd.github.io/'
languageCode = 'en-us'
title = 'Duly Noted'

disableKinds = ["taxonomy"]
enableRobotsTXT = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[imaging]
    quality = 75

[params]
    academic_year = "'25-'26"
    copyright_year = "2025"

[params.auditions]
    status = "CLOSED UNTIL FALL 2025"

[params.social.instagram]
    handle = "@dulynotedatucsd"
    url = "https://www.instagram.com/dulynotedatucsd/"
[params.social.email]
    handle = "dulynotedatucsd@gmail.com"
    url = "mailto:dulynotedatucsd@gmail.com"
[params.social.tiktok]
    url = "https://www.tiktok.com/@dulynotedatucsd"
[params.social.facebook]
    url = "https://www.facebook.com/dulynotedatucsd"
[params.social.youtube]
    url = "https://www.youtube.com/@dulynotedatucsd"
# [params.social.donate]
